### ISSUE TITLE
执行2端口扫描会报错

### ISSUE THREAD

**Issue by y0rkl4u** [Echocipher/AUTO-EARN#1]
AUTOEARN数据库连接成功
读取子域数据库失败
读取子域数据库成功
开启线程：Thread-0
开启线程：Thread-1
开启线程：Thread-2
开启线程：Thread-3
开启线程：Thread-4
开启线程：Thread-5
开启线程：Thread-6
开启线程：Thread-7
开启线程：Thread-8
开启线程：Thread-9
Traceback (most recent call last):
  File "autoearn.py", line 122, in main
    from lib import port_check
  File "/Users/yliu//github/AUTO-EARN/lib/port_check.py", line 162, in <module>
    for domain in domainList:
TypeError: 'NoneType' object is not iterable

**Comment by Echocipher** [comment]
这里应该是没有获取到`domain`呢，`domain`是从`SUBDOMAIN`表中读到的，你可以看一下`./results/result.sqlite3`中的`SUBDOMAIN`表中里面有没有数据呢，如果没有可能是`subdomain_monitor.py`那边出问题了，可以查看一下`logs/subdomain_monitor.log `日志里面的内容，可能是没有`sh stop.sh`和`sh start.sh`就又添加新目标执行`autoearn.py`了，`subdomain_monitor.py`只会在`sh start.sh`之后开启，完成一次任务后结束，之后如果不重新`sh stop.sh`和`sh start.sh`就会无法写入数据库和完成通知提醒

**Comment by y0rkl4u** [comment]
MS没建上表，库里是空的

**Comment by Echocipher** [comment]
建表过程是在子域名收集结束之后调用`lib/server_push.py`进行通知提醒以及数据库建立的，您这边是已经子域名收集完成收到通知了，但是库里没有表吗？

**Comment by y0rkl4u** [comment]
额必须1进行完才能进行2呀，还以为可以异步进行，那可能是我这还没进行完我就选择2了，我重新试一下

**Comment by Echocipher** [comment]
是的 因为是样例版本，所以只能这样顺序执行，之后我会试着改进一下，建议您这边重新
```
sh stop.sh
sh start.sh
python3 autoearn.py
```
然后先`1`，等收到通知后，再`2`，再`4`，这样应该就没什么问题了

**Comment by y0rkl4u** [comment]
了解了，3Q

**Comment by y0rkl4u** [comment]
我的原因是因为mac上执行ps -aux报错了，将subdomain_monitor.py中的命令改为
cmd = "ps aux | grep oneforall.py | grep -v grep | awk '{print $2}'" 一切正常了

**Comment by wikipurse** [comment]
docker 安装的  5000端口访问不了
